# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated. Do not edit manually.
# Run `pytest dimos/robot/test_all_blueprints_generation.py` to regenerate.

all_blueprints = {
    "coordinator-basic": "dimos.control.blueprints.basic:coordinator_basic",
    "coordinator-cartesian-ik-mock": "dimos.control.blueprints.teleop:coordinator_cartesian_ik_mock",
    "coordinator-cartesian-ik-piper": "dimos.control.blueprints.teleop:coordinator_cartesian_ik_piper",
    "coordinator-combined-xarm6": "dimos.control.blueprints.teleop:coordinator_combined_xarm6",
    "coordinator-dual-mock": "dimos.control.blueprints.dual:coordinator_dual_mock",
    "coordinator-dual-xarm": "dimos.control.blueprints.dual:coordinator_dual_xarm",
    "coordinator-mobile-manip-mock": "dimos.control.blueprints.mobile:coordinator_mobile_manip_mock",
    "coordinator-mock": "dimos.control.blueprints.basic:coordinator_mock",
    "coordinator-mock-twist-base": "dimos.control.blueprints.mobile:coordinator_mock_twist_base",
    "coordinator-piper": "dimos.control.blueprints.basic:coordinator_piper",
    "coordinator-piper-xarm": "dimos.control.blueprints.dual:coordinator_piper_xarm",
    "coordinator-servo-xarm6": "dimos.control.blueprints.teleop:coordinator_servo_xarm6",
    "coordinator-teleop-dual": "dimos.control.blueprints.teleop:coordinator_teleop_dual",
    "coordinator-teleop-piper": "dimos.control.blueprints.teleop:coordinator_teleop_piper",
    "coordinator-teleop-xarm6": "dimos.control.blueprints.teleop:coordinator_teleop_xarm6",
    "coordinator-teleop-xarm7": "dimos.control.blueprints.teleop:coordinator_teleop_xarm7",
    "coordinator-velocity-xarm6": "dimos.control.blueprints.teleop:coordinator_velocity_xarm6",
    "coordinator-xarm6": "dimos.control.blueprints.basic:coordinator_xarm6",
    "coordinator-xarm7": "dimos.control.blueprints.basic:coordinator_xarm7",
    "demo-agent": "dimos.agents.demo_agent:demo_agent",
    "demo-agent-camera": "dimos.agents.demo_agent:demo_agent_camera",
    "demo-camera": "dimos.hardware.sensors.camera.module:demo_camera",
    "demo-error-on-name-conflicts": "dimos.robot.unitree.demo_error_on_name_conflicts:demo_error_on_name_conflicts",
    "demo-google-maps-skill": "dimos.agents.skills.demo_google_maps_skill:demo_google_maps_skill",
    "demo-gps-nav": "dimos.agents.skills.demo_gps_nav:demo_gps_nav",
    "demo-grasping": "dimos.manipulation.grasping.demo_grasping:demo_grasping",
    "demo-mcp-stress-test": "dimos.core.tests.stress_test_blueprint:demo_mcp_stress_test",
    "demo-object-scene-registration": "dimos.perception.demo_object_scene_registration:demo_object_scene_registration",
    "demo-osm": "dimos.mapping.osm.demo_osm:demo_osm",
    "demo-skill": "dimos.agents.skills.demo_skill:demo_skill",
    "drone-agentic": "dimos.robot.drone.blueprints.agentic.drone_agentic:drone_agentic",
    "drone-basic": "dimos.robot.drone.blueprints.basic.drone_basic:drone_basic",
    "dual-xarm6-planner": "dimos.manipulation.blueprints:dual_xarm6_planner",
    "keyboard-teleop-piper": "dimos.robot.manipulators.piper.blueprints:keyboard_teleop_piper",
    "keyboard-teleop-xarm6": "dimos.robot.manipulators.xarm.blueprints:keyboard_teleop_xarm6",
    "keyboard-teleop-xarm7": "dimos.robot.manipulators.xarm.blueprints:keyboard_teleop_xarm7",
    "mid360": "dimos.hardware.sensors.lidar.livox.livox_blueprints:mid360",
    "mid360-fastlio": "dimos.hardware.sensors.lidar.fastlio2.fastlio_blueprints:mid360_fastlio",
    "mid360-fastlio-voxels": "dimos.hardware.sensors.lidar.fastlio2.fastlio_blueprints:mid360_fastlio_voxels",
    "mid360-fastlio-voxels-native": "dimos.hardware.sensors.lidar.fastlio2.fastlio_blueprints:mid360_fastlio_voxels_native",
    "teleop-phone": "dimos.teleop.phone.blueprints:teleop_phone",
    "teleop-phone-go2": "dimos.teleop.phone.blueprints:teleop_phone_go2",
    "teleop-phone-go2-fleet": "dimos.teleop.phone.blueprints:teleop_phone_go2_fleet",
    "teleop-quest-dual": "dimos.teleop.quest.blueprints:teleop_quest_dual",
    "teleop-quest-piper": "dimos.teleop.quest.blueprints:teleop_quest_piper",
    "teleop-quest-rerun": "dimos.teleop.quest.blueprints:teleop_quest_rerun",
    "teleop-quest-xarm6": "dimos.teleop.quest.blueprints:teleop_quest_xarm6",
    "teleop-quest-xarm7": "dimos.teleop.quest.blueprints:teleop_quest_xarm7",
    "uintree-g1-primitive-no-nav": "dimos.robot.unitree.g1.blueprints.primitive.uintree_g1_primitive_no_nav:uintree_g1_primitive_no_nav",
    "unitree-g1": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1:unitree_g1",
    "unitree-g1-agentic": "dimos.robot.unitree.g1.blueprints.agentic.unitree_g1_agentic:unitree_g1_agentic",
    "unitree-g1-agentic-sim": "dimos.robot.unitree.g1.blueprints.agentic.unitree_g1_agentic_sim:unitree_g1_agentic_sim",
    "unitree-g1-basic": "dimos.robot.unitree.g1.blueprints.basic.unitree_g1_basic:unitree_g1_basic",
    "unitree-g1-basic-sim": "dimos.robot.unitree.g1.blueprints.basic.unitree_g1_basic_sim:unitree_g1_basic_sim",
    "unitree-g1-detection": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_detection:unitree_g1_detection",
    "unitree-g1-full": "dimos.robot.unitree.g1.blueprints.agentic.unitree_g1_full:unitree_g1_full",
    "unitree-g1-joystick": "dimos.robot.unitree.g1.blueprints.basic.unitree_g1_joystick:unitree_g1_joystick",
    "unitree-g1-shm": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_shm:unitree_g1_shm",
    "unitree-g1-sim": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_sim:unitree_g1_sim",
    "unitree-go2": "dimos.robot.unitree.go2.blueprints.smart.unitree_go2:unitree_go2",
    "unitree-go2-agentic": "dimos.robot.unitree.go2.blueprints.agentic.unitree_go2_agentic:unitree_go2_agentic",
    "unitree-go2-agentic-huggingface": "dimos.robot.unitree.go2.blueprints.agentic.unitree_go2_agentic_huggingface:unitree_go2_agentic_huggingface",
    "unitree-go2-agentic-ollama": "dimos.robot.unitree.go2.blueprints.agentic.unitree_go2_agentic_ollama:unitree_go2_agentic_ollama",
    "unitree-go2-basic": "dimos.robot.unitree.go2.blueprints.basic.unitree_go2_basic:unitree_go2_basic",
    "unitree-go2-coordinator": "dimos.robot.unitree.go2.blueprints.basic.unitree_go2_coordinator:unitree_go2_coordinator",
    "unitree-go2-detection": "dimos.robot.unitree.go2.blueprints.smart.unitree_go2_detection:unitree_go2_detection",
    "unitree-go2-fleet": "dimos.robot.unitree.go2.blueprints.basic.unitree_go2_fleet:unitree_go2_fleet",
    "unitree-go2-ros": "dimos.robot.unitree.go2.blueprints.smart.unitree_go2_ros:unitree_go2_ros",
    "unitree-go2-spatial": "dimos.robot.unitree.go2.blueprints.smart.unitree_go2_spatial:unitree_go2_spatial",
    "unitree-go2-temporal-memory": "dimos.robot.unitree.go2.blueprints.agentic.unitree_go2_temporal_memory:unitree_go2_temporal_memory",
    "unitree-go2-vlm-stream-test": "dimos.robot.unitree.go2.blueprints.smart.unitree_go2_vlm_stream_test:unitree_go2_vlm_stream_test",
    "unitree-go2-nav-coordinator": "dimos.robot.unitree.go2.blueprints.smart.unitree_go2_nav_coordinator:unitree_go2_nav_coordinator",
    "unitree-go2-webrtc-keyboard-teleop": "dimos.robot.unitree.go2.blueprints.basic.unitree_go2_webrtc_keyboard_teleop:unitree_go2_webrtc_keyboard_teleop",
    "unity-sim": "dimos.simulation.unity.blueprint:unity_sim",
    "xarm-perception": "dimos.manipulation.blueprints:xarm_perception",
    "xarm-perception-agent": "dimos.manipulation.blueprints:xarm_perception_agent",
    "xarm6-planner-only": "dimos.manipulation.blueprints:xarm6_planner_only",
    "xarm7-planner-coordinator": "dimos.manipulation.blueprints:xarm7_planner_coordinator",
    "xarm7-planner-coordinator-agent": "dimos.manipulation.blueprints:xarm7_planner_coordinator_agent",
}


all_modules = {
    "arm-teleop-module": "dimos.teleop.quest.quest_extensions.ArmTeleopModule",
    "b-box-navigation-module": "dimos.navigation.bbox_navigation.BBoxNavigationModule",
    "b1-connection-module": "dimos.robot.unitree.b1.connection.B1ConnectionModule",
    "camera-module": "dimos.hardware.sensors.camera.module.CameraModule",
    "cartesian-motion-controller": "dimos.manipulation.control.servo_control.cartesian_motion_controller.CartesianMotionController",
    "control-coordinator": "dimos.control.coordinator.ControlCoordinator",
    "cost-mapper": "dimos.mapping.costmapper.CostMapper",
    "demo-calculator-skill": "dimos.agents.skills.demo_calculator_skill.DemoCalculatorSkill",
    "demo-robot": "dimos.agents.skills.demo_robot.DemoRobot",
    "detection2-d-module": "dimos.perception.detection.module2D.Detection2DModule",
    "detection3-d-module": "dimos.perception.detection.module3D.Detection3DModule",
    "drone-camera-module": "dimos.robot.drone.camera_module.DroneCameraModule",
    "drone-connection-module": "dimos.robot.drone.connection_module.DroneConnectionModule",
    "drone-tracking-module": "dimos.robot.drone.drone_tracking_module.DroneTrackingModule",
    "embedding-memory": "dimos.memory.embedding.EmbeddingMemory",
    "emitter-module": "dimos.utils.demo_image_encoding.EmitterModule",
    "fast-lio2": "dimos.hardware.sensors.lidar.fastlio2.module.FastLio2",
    "foxglove-bridge": "dimos.robot.foxglove_bridge.FoxgloveBridge",
    "g1-connection": "dimos.robot.unitree.g1.connection.G1Connection",
    "g1-connection-base": "dimos.robot.unitree.g1.connection.G1ConnectionBase",
    "g1-sim-connection": "dimos.robot.unitree.g1.sim.G1SimConnection",
    "go2-connection": "dimos.robot.unitree.go2.connection.GO2Connection",
    "go2-fleet-connection": "dimos.robot.unitree.go2.fleet_connection.Go2FleetConnection",
    "google-maps-skill-container": "dimos.agents.skills.google_maps_skill_container.GoogleMapsSkillContainer",
    "gps-nav-skill-container": "dimos.agents.skills.gps_nav_skill.GpsNavSkillContainer",
    "grasp-gen-module": "dimos.manipulation.grasping.graspgen_module.GraspGenModule",
    "grasping-module": "dimos.manipulation.grasping.grasping.GraspingModule",
    "gstreamer-camera-module": "dimos.hardware.sensors.camera.gstreamer.gstreamer_camera.GstreamerCameraModule",
    "joint-trajectory-controller": "dimos.manipulation.control.trajectory_controller.joint_trajectory_controller.JointTrajectoryController",
    "joystick-module": "dimos.robot.unitree.b1.joystick_module.JoystickModule",
    "keyboard-teleop": "dimos.robot.unitree.keyboard_teleop.KeyboardTeleop",
    "keyboard-teleop-module": "dimos.teleop.keyboard.keyboard_teleop_module.KeyboardTeleopModule",
    "manipulation-module": "dimos.manipulation.manipulation_module.ManipulationModule",
    "map": "dimos.robot.unitree.type.map.Map",
    "mcp-client": "dimos.agents.mcp.mcp_client.McpClient",
    "mcp-server": "dimos.agents.mcp.mcp_server.McpServer",
    "mock-b1-connection-module": "dimos.robot.unitree.b1.connection.MockB1ConnectionModule",
    "module-a": "dimos.robot.unitree.demo_error_on_name_conflicts.ModuleA",
    "module-b": "dimos.robot.unitree.demo_error_on_name_conflicts.ModuleB",
    "navigation-module": "dimos.robot.unitree.rosnav.NavigationModule",
    "navigation-skill-container": "dimos.agents.skills.navigation.NavigationSkillContainer",
    "object-db-module": "dimos.perception.detection.moduleDB.ObjectDBModule",
    "object-scene-registration-module": "dimos.perception.object_scene_registration.ObjectSceneRegistrationModule",
    "object-tracker2-d": "dimos.perception.object_tracker_2d.ObjectTracker2D",
    "object-tracker3-d": "dimos.perception.object_tracker_3d.ObjectTracker3D",
    "object-tracking": "dimos.perception.object_tracker.ObjectTracking",
    "osm-skill": "dimos.agents.skills.osm.OsmSkill",
    "patrolling-module": "dimos.navigation.patrolling.module.PatrollingModule",
    "perceive-loop-skill": "dimos.perception.perceive_loop_skill.PerceiveLoopSkill",
    "person-follow-skill-container": "dimos.agents.skills.person_follow.PersonFollowSkillContainer",
    "person-tracker": "dimos.perception.detection.person_tracker.PersonTracker",
    "phone-teleop-module": "dimos.teleop.phone.phone_teleop_module.PhoneTeleopModule",
    "pick-and-place-module": "dimos.manipulation.pick_and_place_module.PickAndPlaceModule",
    "quest-teleop-module": "dimos.teleop.quest.quest_teleop_module.QuestTeleopModule",
    "real-sense-camera": "dimos.hardware.sensors.camera.realsense.camera.RealSenseCamera",
    "receiver-module": "dimos.utils.demo_image_encoding.ReceiverModule",
    "reid-module": "dimos.perception.detection.reid.module.ReidModule",
    "replanning-a-star-planner": "dimos.navigation.replanning_a_star.module.ReplanningAStarPlanner",
    "rerun-bridge-module": "dimos.visualization.rerun.bridge.RerunBridgeModule",
    "ros-nav": "dimos.navigation.rosnav.ROSNav",
    "simple-phone-teleop": "dimos.teleop.phone.phone_extensions.SimplePhoneTeleop",
    "spatial-memory": "dimos.perception.spatial_perception.SpatialMemory",
    "speak-skill": "dimos.agents.skills.speak_skill.SpeakSkill",
    "temporal-memory": "dimos.perception.experimental.temporal_memory.temporal_memory.TemporalMemory",
    "twist-teleop-module": "dimos.teleop.quest.quest_extensions.TwistTeleopModule",
    "unitree-g1-skill-container": "dimos.robot.unitree.g1.skill_container.UnitreeG1SkillContainer",
    "unitree-skill-container": "dimos.robot.unitree.unitree_skill_container.UnitreeSkillContainer",
    "unity-bridge-module": "dimos.simulation.unity.module.UnityBridgeModule",
    "vlm-agent": "dimos.agents.vlm_agent.VLMAgent",
    "vlm-stream-tester": "dimos.agents.vlm_stream_tester.VlmStreamTester",
    "voxel-grid-mapper": "dimos.mapping.voxels.VoxelGridMapper",
    "wavefront-frontier-explorer": "dimos.navigation.frontier_exploration.wavefront_frontier_goal_selector.WavefrontFrontierExplorer",
    "web-input": "dimos.agents.web_human_input.WebInput",
    "websocket-vis-module": "dimos.web.websocket_vis.websocket_vis_module.WebsocketVisModule",
    "zed-camera": "dimos.hardware.sensors.camera.zed.camera.ZEDCamera",
}
